import mongoose from "mongoose";

const UserSchema = new mongoose.Schema(
  {
    Sno: String,
    EmpId: String,
    Name: String,
    DOJ: String,
    ActivationStatus: String,
    Division: String,
    Designation: String,
    Zone:String,
    State: String,
    City: String,
    Location: String,
    CityZone: String,
    Head: String,
    Company: String,
    Salary: String,
    MDay: String,
    PaidDays: String,
    Basic: String,
    DA:String,
    HRA: String,
    CON: String,
    SpeicalAllowence: String,
    OtherAllowence: String,
    Gross:String,
    Empesic: String,
    Emppf: String,
    Emplwf: String,
    ProfessionalTax: String,
    ETD:String,
    AmountPaid: String,
    Admin1: String,
    PetrolAllowence:String,
    MoblieAllowence:String,
    OtherExp: String,
    NetTakeHome: String,
    Incentive: String,
    Amount: String,
    DeductionInAdvance: String,
    NetAmountPaid: String,
    Remarks: String,
    AccountNo: String,
    IfscCode: String,
    BankName: String,
    AccountName:String,
    role: {
      type: String,
      enum: ["user", "admin", "superadmin"],
      default: "user",
    },

  },
  { timestamps: true }
);

const User = mongoose.model("User", UserSchema);
export default User;
